### ISSUE TITLE
Can not compile the project

### ISSUE THREAD

**Issue by onlyice** [C0deH4cker/SimpleGameEngine#2]
I clone the repo and run `make` command, it says:

```
mkdir -p build
make sge
make[1]: Entering directory '/home/onlyice/work/flappy-bird/SimpleGameEngine'
make[1]: *** No rule to make target 'build/Camera.o', needed by 'sge'.  Stop.
make[1]: Leaving directory '/home/onlyice/work/flappy-bird/SimpleGameEngine'
Makefile:35: recipe for target 'all' failed
make: *** [all] Error 2
```

I'll appreciate it if you fix that and provide some documents, so I can learn how you write a game engine. Thanks in advanced.

**Comment by C0deH4cker** [comment]
Fixed, thanks for spotting this. And I do plan on adding more documentation once SGE is more developed.
